name: Deploy Web (GitHub Pages)

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'
      - '.github/workflows/deploy-web.yml'
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        working-directory: web
        run: npm ci

      - name: Derive GitHub Pages base path
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          echo "Derived repo name: $REPO_NAME"
          echo "VITE_BASE_PATH=/$REPO_NAME/" >> $GITHUB_ENV
          echo "Using base path: /$REPO_NAME/"

      - name: Build
        working-directory: web
        env:
          VITE_STACKS_NETWORK: testnet
          # Provide this via repository secret (Settings > Secrets > Actions)
          # Add VITE_CONTRACT_ADDRESS later as a secret; empty default keeps build working
          VITE_CONTRACT_ADDRESS: ""
          VITE_APP_NAME: 'PMA Web'
          VITE_APP_ICON: 'https://placehold.co/64x64'
        run: npm run build

      - name: Add SPA fallback & nojekyll
        run: |
          cp web/dist/index.html web/dist/404.html
          touch web/dist/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
